Numpy-numerical python

In [2]:
import numpy as np

creating array from list


In [3]:
arr_1d =np.array([1,2,3,4,6,7])
print("1D array is",arr_1d)

1D array is [1 2 3 4 6 7]


In [4]:
arr_2d=np.array([[1,2,3],[4,6,7]])
print("2d array is",arr_2d)

2d array is [[1 2 3]
 [4 6 7]]


List vs Numpy Array

In [5]:
py_list=[1,2,3]
print("python muiltiplication is",py_list * 2)

python muiltiplication is [1, 2, 3, 1, 2, 3]


In [6]:
np_array=np.array([1,2,3])
print("python array ",np_array*2)

python array  [2 4 6]


In [7]:
import time
start=time.time()
py_list=[i*2 for i in range(10000000)]
print("\n list opeartion time ",time.time()-start)


 list opeartion time  0.8591177463531494


In [8]:
import time
start=time.time()
np_array=np.arange(10000000)
print("\n numpy opeartion time ",time.time()-start)


 numpy opeartion time  0.009547710418701172


Creating array from scratch


In [9]:
zeros=np.zeros((4,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full=np.full((3,3),4)
print(full)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [12]:
random=np.random.random((2,3))
print(random)

[[0.32807125 0.63215311 0.85639145]
 [0.09424675 0.41681619 0.40024715]]


In [15]:
sequence=np.arange(0,12,2)
print(sequence)

[ 0  2  4  6  8 10]


Vector Matrix and Tensor

In [16]:
vector=np.array([1,2,3])
print("vector",vector)

vector [1 2 3]


In [17]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [20]:
tensor=np.array([[[1,2],[3,4],[5,6],[7,8],[9,0]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]
  [9 0]]]


Array properties


In [22]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("shape ",arr.shape)
print('dimension',arr.ndim)
print("size",arr.size)
print("data type ",arr.dtype)

shape  (3, 3)
dimension 2
size 9
data type  int32


Array reshaping

In [23]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
reshaped=arr.reshape((3,4))
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
flat=reshaped.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled=reshaped.ravel()
print(raveled)

#ravel (return view instead of copy) (it return original array while flatten return copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
transpose=reshaped.T
print(transpose)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
