Numpy-numerical python

In [2]:
import numpy as np

creating array from list


In [ ]:
arr_1d =np.array([1,2,3,4,6,7])
print("1D array is",arr_1d)

1D arrayis [1 2 3 4 6 7]


In [4]:
arr_2d=np.array([[1,2,3],[4,6,7]])
print("2d array is",arr_2d)

2d array is [[1 2 3]
 [4 6 7]]


List vs Numpy Array

In [8]:
py_list=[1,2,3]
print("python muiltiplication is",py_list * 2)

python muiltiplication is [1, 2, 3, 1, 2, 3]


In [9]:
np_array=np.array([1,2,3])
print("python array ",np_array*2)

python array  [2 4 6]


In [13]:
import time
start=time.time()
py_list=[i*2 for i in range(10000000)]
print("\n list opeartion time ",time.time()-start)


 list opeartion time  0.7464675903320312


In [19]:
import time
start=time.time()
np_array=np.arange(10000000)
print("\n numpy opeartion time ",time.time()-start)


 numpy opeartion time  0.011752605438232422


Creating array from scratch


In [24]:
zeros=np.zeros((4,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
full=np.full((3,3),4)
print(full)

[[4 4 4]
 [4 4 4]
 [4 4 4]]
