##Numpy Array operation

In [1]:
import numpy as np

In [4]:
arr=np.arange(1,15)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
print(arr[3:8])

[4 5 6 7 8]


In [6]:
print(arr[2:9:2])

[3 5 7 9]


In [ ]:
print("negative indexing",arr[-3])
#last third value 

negative indexing 12


In [8]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print("specific element",arr_2d[1,2])

specific element 6


In [11]:
print("entire row",arr_2d[1])

entire row [4 5 6]


In [12]:
print("entire column",arr_2d[:,1])

entire column [2 5 8]


Sorting


In [13]:
unsorted=np.array([2,6,4,5,9,3,1,0,11])
print(np.sort(unsorted))

[ 0  1  2  3  4  5  6  9 11]


In [16]:
arr=np.array([[3,1],[1,2],[2,3]])
print("sorted 2D array by column",np.sort(arr,axis=0))
print("sorted 2D array by column",np.sort(arr,axis=1))

sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]
