##Numpy Array operation

In [2]:
import numpy as np

In [4]:
arr=np.arange(1,15)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
print(arr[3:8])

[4 5 6 7 8]


In [6]:
print(arr[2:9:2])

[3 5 7 9]


In [ ]:
print("negative indexing",arr[-3])
#last third value 

negative indexing 12


In [8]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print("specific element",arr_2d[1,2])

specific element 6


In [11]:
print("entire row",arr_2d[1])

entire row [4 5 6]


In [12]:
print("entire column",arr_2d[:,1])

entire column [2 5 8]


Sorting


In [13]:
unsorted=np.array([2,6,4,5,9,3,1,0,11])
print(np.sort(unsorted))

[ 0  1  2  3  4  5  6  9 11]


In [16]:
arr=np.array([[3,1],[1,2],[2,3]])
print("sorted 2D array by column",np.sort(arr,axis=0))
print("sorted 2D array by column",np.sort(arr,axis=1))

sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


Filters


In [4]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even=numbers[numbers%2==0]
print(even)

[ 2  4  6  8 10]


## filter with mask


In [5]:
mask=numbers > 5
print(numbers[mask])

[ 6  7  8  9 10]


### fancy indexing vs np.where()

In [6]:
indices=[0,2,4]
print(numbers[indices])

[1 3 5]


In [7]:
where_result=np.where(numbers>5)
print(numbers[where_result])

[ 6  7  8  9 10]


In [8]:
print(where_result)

(array([5, 6, 7, 8, 9], dtype=int64),)


if(condition(number>5)){
    number*2
}
else{
    numbers
}

In [17]:
condition_array=np.where(numbers > 5 ,numbers*2,numbers)
print(condition_array)


[ 1  2  3  4  5 12 14 16 18 20]


## ading and removing data

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=arr1+arr2
print(combined)

[5 7 9]


In [20]:
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


# 
array compatibility

In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])

print("compatibility shapes", a.shape == b.shape )
print("compatibility shapes", a.shape == c.shape )

compatibility shapes True
compatibility shapes False


In [ ]:
original=np.array([[1,2],[3,4],[5,6]])
new=np.array([[7,8]])
#add rows 
with_new=np.vstack((original,new))
print(original,"/n array")
print(with_new)
#adds columns
new_col=np.array([[7],[8],[9]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]] /n array
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
arr=np.array([1,2,3,4,5])
dele=np.delete(arr,3)
print(arr)
print(dele)

[1 2 3 4 5]
[1 2 3 5]
